/**
 * Tests for LocalLLMProvider.generateNegativePrompt()
 * Tests the method integrated into LLM provider
 */

const { describe, it, mock } = require('node:test');
const assert = require('node:assert');
const LocalLLMProvider = require('../../src/providers/local-llm-provider');

describe('LocalLLMProvider - generateNegativePrompt', () => {
  describe('Method exists and basic functionality', () => {
    it('should have generateNegativePrompt method', () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });
      assert.ok(typeof provider.generateNegativePrompt === 'function', 'Should have generateNegativePrompt method');
    });

    it('should return negativePrompt and metadata', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      // Mock the _generate method to avoid actual LLM call
      provider._generate = async () => ({
        text: 'blurry, low quality, distorted',
        usage: { total_tokens: 100 }
      });

      const result = await provider.generateNegativePrompt('a beautiful sunset');

      assert.ok(result.negativePrompt, 'Should have negativePrompt');
      assert.ok(result.metadata, 'Should have metadata');
      assert.strictEqual(typeof result.negativePrompt, 'string', 'negativePrompt should be string');
    });
  });

  describe('Generation with mocked LLM', () => {
    it('should generate intelligent negatives for "30 year old man"', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      provider._generate = async () => ({
        text: 'elderly, aged, wrinkled, senior, young, child, teenager, blurry, low quality',
        usage: { total_tokens: 150 }
      });

      const result = await provider.generateNegativePrompt('30 year old man');

      assert.ok(result.negativePrompt.includes('elderly') || result.negativePrompt.includes('aged'));
      assert.ok(result.metadata.autoGenerated, 'Should mark as auto-generated');
      assert.ok(result.metadata.generationTime >= 0, 'Should track time');
    });

    it('should include metadata with token usage', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      provider._generate = async () => ({
        text: 'test negative',
        usage: {
          total_tokens: 123,
          prompt_tokens: 100,
          completion_tokens: 23
        }
      });

      const result = await provider.generateNegativePrompt('test prompt');

      assert.strictEqual(result.metadata.tokensUsed, 123);
      assert.strictEqual(result.metadata.promptTokens, 100);
      assert.strictEqual(result.metadata.completionTokens, 23);
    });
  });

  describe('Options and configuration', () => {
    it('should respect enabled=false option', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      const result = await provider.generateNegativePrompt('test', { enabled: false });

      assert.strictEqual(result.negativePrompt, '', 'Should return empty when disabled');
      assert.strictEqual(result.metadata.autoGenerated, false);
    });

    it('should use custom fallback when provided', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      // Mock failure
      provider._generate = async () => {
        throw new Error('LLM unavailable');
      };

      const customFallback = 'custom, fallback, negative';
      const result = await provider.generateNegativePrompt('test', { fallback: customFallback });

      assert.strictEqual(result.negativePrompt, customFallback);
      assert.strictEqual(result.metadata.usedFallback, true);
    });

    it('should use default fallback when LLM fails', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      provider._generate = async () => {
        throw new Error('LLM service down');
      };

      const result = await provider.generateNegativePrompt('test');

      assert.ok(result.negativePrompt.includes('blurry'));
      assert.ok(result.negativePrompt.includes('low quality'));
      assert.strictEqual(result.metadata.usedFallback, true);
      assert.ok(result.metadata.error);
    });
  });

  describe('Edge cases', () => {
    it('should handle empty prompt', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      const result = await provider.generateNegativePrompt('');

      assert.ok(result.negativePrompt, 'Should return fallback for empty prompt');
      assert.strictEqual(result.metadata.usedFallback, true);
    });

    it('should handle whitespace-only prompt', async () => {
      const provider = new LocalLLMProvider({ apiUrl: 'http://localhost:8003' });

      const result = await provider.generateNegativePrompt('   ');

      assert.ok(result.negativePrompt, 'Should return fallback for whitespace');
      assert.strictEqual(result.metadata.usedFallback, true);
    });
  });
});
