/**
 * Tests for Negative Prompt Generator
 * TDD RED phase - these tests should fail initially
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert');
const NegativePromptGenerator = require('../../src/utils/negative-prompt-generator');

describe('NegativePromptGenerator', () => {
  let generator;

  before(() => {
    // Create generator with mock LLM provider
    const mockLLMProvider = {
      async generateCompletion(prompt, options) {
        // Mock response simulating Mistral 7B output
        if (prompt.includes('30 year old man')) {
          return {
            text: 'elderly, aged, wrinkled, senior, young, child, teenager, blurry, low quality, distorted'
          };
        }
        return {
          text: 'blurry, low quality, distorted, deformed'
        };
      }
    };

    generator = new NegativePromptGenerator({
      llmProvider: mockLLMProvider
    });
  });

  describe('generateNegativePrompt', () => {
    it('should generate negative prompt from positive prompt', async () => {
      const result = await generator.generateNegativePrompt('a beautiful landscape');

      assert.ok(result.negativePrompt, 'Should return negative prompt');
      assert.ok(typeof result.negativePrompt === 'string', 'Should be a string');
      assert.ok(result.negativePrompt.length > 0, 'Should not be empty');
    });

    it('should include quality negatives by default', async () => {
      const result = await generator.generateNegativePrompt('a portrait');

      const lower = result.negativePrompt.toLowerCase();
      assert.ok(
        lower.includes('blurry') || lower.includes('low quality'),
        'Should include quality negatives'
      );
    });

    it('should handle "30 year old man" case correctly', async () => {
      const result = await generator.generateNegativePrompt('30 year old man');

      const lower = result.negativePrompt.toLowerCase();
      // Should prevent "old" misinterpretation
      assert.ok(
        lower.includes('elderly') || lower.includes('aged'),
        'Should include elderly/aged to prevent "old" misinterpretation'
      );
      // Should also prevent too young
      assert.ok(
        lower.includes('young') || lower.includes('child'),
        'Should include young/child to prevent too young'
      );
    });

    it('should return metadata about generation', async () => {
      const result = await generator.generateNegativePrompt('test prompt');

      assert.ok(result.metadata, 'Should include metadata');
      assert.ok(result.metadata.model, 'Should include model name');
      assert.ok(typeof result.metadata.generationTime === 'number', 'Should include generation time');
    });

    it('should allow disabling auto-generation', async () => {
      const result = await generator.generateNegativePrompt('test', {
        enabled: false
      });

      assert.strictEqual(result.negativePrompt, '', 'Should return empty when disabled');
      assert.strictEqual(result.metadata.autoGenerated, false, 'Should mark as not auto-generated');
    });

    it('should support custom fallback negative prompt', async () => {
      const fallback = 'custom, fallback, negative';
      const result = await generator.generateNegativePrompt('test', {
        fallback
      });

      // If LLM fails, should use fallback
      // For now, just test that fallback is stored in metadata
      assert.ok(result.metadata, 'Should have metadata');
    });
  });

  describe('Error handling', () => {
    it('should handle LLM service errors gracefully', async () => {
      const failingGenerator = new NegativePromptGenerator({
        llmProvider: {
          async generateCompletion() {
            throw new Error('LLM service unavailable');
          }
        }
      });

      const result = await failingGenerator.generateNegativePrompt('test', {
        fallback: 'blurry, low quality'
      });

      // Should fallback to default negative when LLM fails
      assert.ok(result.negativePrompt, 'Should return fallback negative');
      assert.ok(result.metadata.error, 'Should include error in metadata');
      assert.strictEqual(result.metadata.autoGenerated, false, 'Should mark as not auto-generated');
    });

    it('should handle empty prompts', async () => {
      const result = await generator.generateNegativePrompt('');

      assert.ok(result.negativePrompt !== undefined, 'Should handle empty prompt');
    });
  });
});
