/**
 * Integration tests for Modal SDXL with auto-generated negative prompts
 * TDD: Test the full pipeline with NegativePromptGenerator
 */

const { describe, it, before } = require('node:test');
const assert = require('node:assert');
const NegativePromptGenerator = require('../../src/utils/negative-prompt-generator');

describe('Modal SDXL with Auto-Generated Negative Prompts', () => {
  let generator;
  let mockLLMProvider;

  before(() => {
    // Mock LLM provider for testing
    mockLLMProvider = {
      async generateCompletion(prompt) {
        // Simulate intelligent negative prompt generation
        if (prompt.includes('30 year old man')) {
          return {
            text: 'elderly, aged, wrinkled, senior, young, child, teenager, blurry, low quality',
            model: 'mock-llm'
          };
        }
        return {
          text: 'blurry, low quality, distorted',
          model: 'mock-llm'
        };
      }
    };

    generator = new NegativePromptGenerator({
      llmProvider: mockLLMProvider
    });
  });

  describe('SDXL negative prompt generation', () => {
    it('should generate negative prompts for SDXL models', async () => {
      const positivePrompt = 'a beautiful portrait of a 30 year old woman';

      const result = await generator.generateNegativePrompt(positivePrompt);

      assert.ok(result.negativePrompt, 'Should generate negative prompt');
      assert.ok(result.metadata.autoGenerated, 'Should mark as auto-generated');
      assert.ok(result.metadata.generationTime >= 0, 'Should track generation time');
    });

    it('should work with combined prompts from beam search', async () => {
      // Simulate combined prompt from beam search (what + how)
      const combinedPrompt = 'a portrait of a woman, photorealistic, studio lighting, professional photography';

      const result = await generator.generateNegativePrompt(combinedPrompt);

      assert.ok(result.negativePrompt.length > 0, 'Should generate negative for combined prompt');
    });

    it('should handle long prompts (Compel compatibility)', async () => {
      // Long prompt that would benefit from Compel
      const longPrompt = 'a highly detailed portrait of a young woman with flowing hair, '
        + 'wearing an elegant dress, standing in a beautiful garden with flowers, '
        + 'soft natural lighting, golden hour, bokeh background, cinematic composition, '
        + 'professional photography, 8k resolution, photorealistic';

      const result = await generator.generateNegativePrompt(longPrompt);

      assert.ok(result.negativePrompt, 'Should handle long prompts');
      // Negative prompt can also be long (Compel will handle it)
      assert.ok(result.metadata.autoGenerated, 'Should successfully generate');
    });

    it('should allow manual negative prompt override', async () => {
      const positivePrompt = 'a sunset';
      const manualNegative = 'custom manual negative prompt';

      // When user provides manual negative, should not auto-generate
      const result = await generator.generateNegativePrompt(positivePrompt, {
        enabled: false
      });

      assert.strictEqual(result.negativePrompt, '', 'Should return empty when disabled');
      assert.strictEqual(result.metadata.autoGenerated, false, 'Should mark as manual');
    });

    it('should include generation metadata in response', async () => {
      const result = await generator.generateNegativePrompt('test prompt');

      assert.ok(result.metadata, 'Should include metadata');
      assert.ok(result.metadata.model, 'Should include model name');
      assert.ok(typeof result.metadata.generationTime === 'number', 'Should include timing');
      assert.ok(typeof result.metadata.autoGenerated === 'boolean', 'Should include auto-gen flag');
    });
  });

  describe('Integration with Modal diffusion options', () => {
    it('should pass negative prompt to Modal generate request', async () => {
      // Simulate Modal generate request structure
      const modalRequest = {
        prompt: '30 year old man',
        model: 'sdxl-base',
        width: 1024,
        height: 1024,
        steps: 30,
        guidance: 7.5
      };

      // Generate negative prompt
      const { negativePrompt, metadata } = await generator.generateNegativePrompt(modalRequest.prompt);

      // Should be able to add to Modal request
      const enhancedRequest = {
        ...modalRequest,
        negative_prompt: negativePrompt
      };

      assert.ok(enhancedRequest.negative_prompt, 'Should add negative_prompt to request');
      assert.ok(enhancedRequest.negative_prompt.includes('elderly'), 'Should have intelligent negatives');
    });

    it('should work with Flux models (skip for non-SDXL)', async () => {
      const fluxRequest = {
        prompt: 'test',
        model: 'flux-dev' // Not SDXL
      };

      // For Flux, might skip negative prompt generation (or handle differently)
      // This test documents the behavior
      const result = await generator.generateNegativePrompt(fluxRequest.prompt, {
        enabled: true // Can still generate if requested
      });

      assert.ok(result.negativePrompt, 'Can generate for any model if enabled');
    });
  });

  describe('Error recovery', () => {
    it('should use fallback when LLM fails', async () => {
      const failingGenerator = new NegativePromptGenerator({
        llmProvider: {
          async generateCompletion() {
            throw new Error('LLM timeout');
          }
        },
        fallback: 'blurry, low quality, distorted'
      });

      const result = await failingGenerator.generateNegativePrompt('test');

      assert.strictEqual(result.negativePrompt, 'blurry, low quality, distorted', 'Should use fallback');
      assert.ok(result.metadata.error, 'Should include error info');
      assert.strictEqual(result.metadata.autoGenerated, false, 'Should mark as not auto-generated');
    });
  });
});
