/**
 * 🔴 TDD RED PHASE: VLM Image Path Integration Test
 *
 * Tests that VLM can read images generated by Modal/BFL providers.
 * Issue #33: Fix 404 errors in VLM comparison endpoint for modal workflow
 *
 * The bug: Modal/BFL providers use relative paths like 'output/2026-02-09/ses-123456/...'
 * but VLM Python service needs absolute paths to read files.
 *
 * The fix: Pass absolute outputDir to image providers via createImageProvider.
 */

const { describe, test, beforeEach, afterEach, mock } = require('node:test');
const assert = require('node:assert');
const path = require('path');
const { createRequire } = require('node:module');

// Get the OUTPUT_DIR that beam-search-worker uses
const OUTPUT_DIR = process.env.SESSION_HISTORY_DIR ||
                   process.env.IMAGES_DIR ||
                   path.join(process.cwd(), 'session-history');

describe('VLM Modal Image Paths Integration', () => {
  describe('Issue #33: Image paths must be absolute for VLM access', () => {
    test('OUTPUT_DIR should be an absolute path', () => {
      // This test verifies the base assumption: OUTPUT_DIR is absolute
      assert.ok(
        path.isAbsolute(OUTPUT_DIR),
        `OUTPUT_DIR should be absolute but got: ${OUTPUT_DIR}`
      );
    });

    test('Modal provider should produce absolute paths when outputDir is absolute', async () => {
      // Mock axios to avoid actual HTTP calls
      const nock = require('nock');

      // Load the actual provider
      const ModalImageProvider = require('../../src/providers/modal-image-provider.js');

      // Create provider with absolute outputDir (like beam-search-worker should do)
      const absoluteOutputDir = path.join(process.cwd(), 'test-output');
      const provider = new ModalImageProvider({
        apiUrl: 'https://test.modal.run',
        tokenId: 'test-token-id',
        tokenSecret: 'test-token-secret',
        sessionId: 'ses-123456',
        outputDir: absoluteOutputDir
      });

      // Mock the Modal API response
      nock('https://test.modal.run')
        .post('/')
        .reply(200, {
          image: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
          format: 'base64'
        });

      try {
        const result = await provider.generateImage('test prompt', {
          iteration: 0,
          candidateId: 0
        });

        // The key assertion: localPath must be absolute
        assert.ok(result.localPath, 'Should have localPath');
        assert.ok(
          path.isAbsolute(result.localPath),
          `localPath should be absolute but got: ${result.localPath}`
        );
      } finally {
        nock.cleanAll();
        // Cleanup test directory if created
        const fs = require('fs').promises;
        try {
          await fs.rm(absoluteOutputDir, { recursive: true, force: true });
        } catch (_e) { /* ignore */ }
      }
    });

    test('Modal provider with default outputDir produces relative paths (BUG)', async () => {
      // This test documents the current buggy behavior
      const ModalImageProvider = require('../../src/providers/modal-image-provider.js');

      // Create provider WITHOUT outputDir - uses default 'output' (relative)
      const provider = new ModalImageProvider({
        apiUrl: 'https://test.modal.run',
        tokenId: 'test-token-id',
        tokenSecret: 'test-token-secret'
      });

      // Default outputDir should be 'output' (relative) - this is the bug
      assert.strictEqual(provider.outputDir, 'output', 'Default outputDir is relative');

      // Now verify the path construction would be relative
      const OutputPathManager = require('../../src/utils/output-path-manager.js');
      const sessionDir = OutputPathManager.buildSessionPath(provider.outputDir, 'ses-test');

      // This assertion shows the bug: path is relative, VLM can't find it
      assert.ok(
        !path.isAbsolute(sessionDir),
        `BUG: sessionDir is relative: ${sessionDir} - VLM cannot read this path`
      );
    });

    test('BFL provider with default outputDir produces relative paths (BUG)', async () => {
      // Same test for BFL provider
      const BFLImageProvider = require('../../src/providers/bfl-image-provider.js');

      // Create provider WITHOUT outputDir - uses default 'output' (relative)
      const provider = new BFLImageProvider({
        apiKey: 'test-api-key'
      });

      // Default outputDir should be 'output' (relative) - this is the bug
      assert.strictEqual(provider.outputDir, 'output', 'Default outputDir is relative');

      const OutputPathManager = require('../../src/utils/output-path-manager.js');
      const sessionDir = OutputPathManager.buildSessionPath(provider.outputDir, 'ses-test');

      // This assertion shows the bug
      assert.ok(
        !path.isAbsolute(sessionDir),
        `BUG: sessionDir is relative: ${sessionDir} - VLM cannot read this path`
      );
    });

    test('beam-search-worker should pass absolute outputDir to createImageProvider', async () => {
      // This test verifies the fix: beam-search-worker passes outputDir to image provider
      // The fix (Issue #33): beam-search-worker now passes outputDir: OUTPUT_DIR

      const { createImageProvider } = require('../../src/factory/provider-factory.js');

      // This simulates what beam-search-worker.js now does (after fix at lines 149-156)
      // The key difference: outputDir: OUTPUT_DIR is now passed!
      const modalProvider = createImageProvider({
        mode: 'real',
        provider: 'modal',
        apiUrl: 'https://test.modal.run',
        tokenId: 'test-token',
        tokenSecret: 'test-secret',
        outputDir: OUTPUT_DIR  // This is now passed by beam-search-worker (Issue #33 fix)
      });

      // Verify the fix works: outputDir should be absolute
      assert.ok(
        path.isAbsolute(modalProvider.outputDir),
        `Modal provider outputDir should be absolute but got: '${modalProvider.outputDir}'`
      );
    });

    test('verify beam-search-worker.js passes outputDir to createImageProvider', async () => {
      // This test verifies the actual code change in beam-search-worker.js
      const fs = require('fs');
      const workerCode = fs.readFileSync(
        path.join(process.cwd(), 'src/api/beam-search-worker.js'),
        'utf8'
      );

      // Check that outputDir: OUTPUT_DIR is passed in the createImageProvider call
      // The fix should add: outputDir: OUTPUT_DIR, in the imageGen provider creation
      assert.ok(
        workerCode.includes('outputDir: OUTPUT_DIR'),
        'beam-search-worker.js should pass outputDir: OUTPUT_DIR to createImageProvider'
      );

      // Also verify it's in the context of createImageProvider call
      const imageGenMatch = workerCode.match(/imageGen:\s*createImageProvider\(\{[\s\S]*?outputDir:\s*OUTPUT_DIR[\s\S]*?\}\)/);
      assert.ok(
        imageGenMatch,
        'outputDir: OUTPUT_DIR should be within the imageGen createImageProvider call'
      );
    });

    test('VLM _getImagePath should work with absolute paths', () => {
      // Test that VLM can handle the paths we provide
      const LocalVLMProvider = require('../../src/providers/local-vlm-provider.js');

      const vlm = new LocalVLMProvider({
        apiUrl: 'http://localhost:8004'
      });

      // Test with absolute path
      const absolutePath = '/home/user/session-history/2026-02-09/ses-123/iter0-cand0.png';
      const image = { localPath: absolutePath, candidateId: 'i0c0' };

      const result = vlm._getImagePath(image);
      assert.strictEqual(result, absolutePath, 'Should return the absolute path');
    });

    test('VLM _getImagePath throws error for URL-only images', () => {
      // VLM requires local files
      const LocalVLMProvider = require('../../src/providers/local-vlm-provider.js');

      const vlm = new LocalVLMProvider({
        apiUrl: 'http://localhost:8004'
      });

      const image = {
        url: 'https://openai-images.example.com/image.png',
        candidateId: 'i0c0'
      };

      assert.throws(
        () => vlm._getImagePath(image),
        /VLM requires local file paths/,
        'Should throw error for URL-only images'
      );
    });
  });

  describe('Provider factory integration', () => {
    test('createImageProvider for modal should accept outputDir', () => {
      const { createImageProvider } = require('../../src/factory/provider-factory.js');

      const provider = createImageProvider({
        mode: 'real',
        provider: 'modal',
        apiUrl: 'https://test.modal.run',
        tokenId: 'test-token',
        tokenSecret: 'test-secret',
        outputDir: '/absolute/path/to/output'
      });

      assert.strictEqual(provider.outputDir, '/absolute/path/to/output');
    });

    test('createImageProvider for bfl should accept outputDir', () => {
      const { createImageProvider } = require('../../src/factory/provider-factory.js');

      const provider = createImageProvider({
        mode: 'real',
        provider: 'bfl',
        apiKey: 'test-api-key',
        outputDir: '/absolute/path/to/output'
      });

      assert.strictEqual(provider.outputDir, '/absolute/path/to/output');
    });
  });
});
